parameters:
  path: "$(System.DefaultWorkingDirectory)"

jobs:
  - job: "Jsonlint"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: |
          sudo apt install -y jsonlint
          for file in $(find $(path) -type f -name "*.json"); do
            if ! jsonlint -q $file; then
              export FAILED=1
            else
              echo "$file OK"
            fi
          done
          if [ "${FAILED}" = "1" ]; then
            exit 1
          fi
        displayName: "Install and Run"
