parameters:
  path: "**/Dockerfile*"
  version: "latest"

jobs:
  - job: "Shellcheck"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: docker pull pipelinecomponents/shellcheck:${{ parameters.version }}
        displayName: "Install"
      - script: |
          apt install -y grep
          docker run --rm -i pipelinecomponents/shellcheck:${{ parameters.version }} --version
          find . -type f -print0 | xargs -0 sed -i 's:#!/usr/bin/with-contenv bash:#!/bin/bash:g'
          for file in $(grep -IRl "#\!\(/usr/bin/env \|/bin/\)" --exclude-dir ".git" "${TARGET}"); do
            if ! docker run --rm -i pipelinecomponents/shellcheck:${{ parameters.version }} $file; then
              export FAILED=1
            else
              echo "$file OK"
            fi
          done
          if [ "${FAILED}" = "1" ]; then
            exit 1
          fi
        displayName: "Run"
