parameters:
  path: "$(System.DefaultWorkingDirectory)"

jobs:
  - job: "YAMLlint"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: sudo apt install yamllint
        displayName: "Install"
      - script: |
          yamllint ${{ parameters.path }}
        displayName: "Run"
