parameters:
  path: "$(System.DefaultWorkingDirectory)"

jobs:
  - job: "ESLint"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - task: Cache@2
        inputs:
          key: 'yarn | "$(Agent.OS)" | yarn.lock'
          path: $(yarnCachePath)
          restoreKeys: |
            yarn | "$(Agent.OS)"
            yarn
        displayName: 'Cache Yarn Packages'
      - script: |
          yarn install --pure-lockfile --cache-folder .yarn
          sudo yarn global add eslint
        displayName: "Install"
      - script: |
          eslint $( [[ -e ${{ parameters.path }}/.eslintrc.json ]] || echo '--no-eslintrc' ) --color ${{ parameters.path }}
        displayName: "Run"
