parameters:
  path: "$(System.DefaultWorkingDirectory)"

jobs:
  - job: "ESLint"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: sudo yarn global add eslint
        displayName: "Install"
      - script: |
          eslint $( [[ -e ${{ parameters.path }}/.eslintrc.json ]] || echo '--no-eslintrc' ) --color ${{ parameters.path }}
        displayName: "Run"
