parameters:
  path: "**/Dockerfile*"
  version: "v1.17.2"

jobs:
  - job: "Hadolint"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: docker pull hadolint/hadolint:${{ parameters.version }}
        displayName: "Install Hadolint"
      - script: |
          set -e
          shopt -s globstar
          for dockerfile in ${{ parameters.path }}
          do
            echo "Linting: $dockerfile"
            docker run --rm -i \
              -v $(pwd)/.hadolint.yaml:/.hadolint.yaml:ro \
              hadolint/hadolint:${{ parameters.version }} < "$dockerfile"
          done
        displayName: "Run Hadolint"
