parameters:
  buildArch: "amd64"
  buildBase: "amd64/alpine:3.11.3"
  githubRepository: "organization"

steps:
  - script: |
      docker info
      docker run --rm --privileged hassioaddons/qemu-user-static:latest
      if [ "${{ parameters.buildArch }}" = "aarch64" ]; then
        mkdir -p $(System.DefaultWorkingDirectory)/rootfs/usr/bin
        curl -L -s \
          "https://github.com/hassio-addons/qemu-user-static/releases/download/v4.2.0/qemu-aarch64-static.tar.gz" | \
          tar zxvf - -C "$(System.DefaultWorkingDirectory)/rootfs/usr/bin/"
      fi
      if [ "${{ parameters.buildArch }}" = "armhf" ]; then
        mkdir -p $(System.DefaultWorkingDirectory)/rootfs/usr/bin
        curl -L -s \
          "https://github.com/hassio-addons/qemu-user-static/releases/download/v4.2.0/qemu-arm-static.tar.gz" | \
          tar zxvf - -C "$(System.DefaultWorkingDirectory)/rootfs/usr/bin/"
      fi
      if [ "${{ parameters.buildArch }}" = "armv7" ]; then
        mkdir -p $(System.DefaultWorkingDirectory)/rootfs/usr/bin
        curl -L -s \
          "https://github.com/hassio-addons/qemu-user-static/releases/download/v4.2.0/qemu-arm-static.tar.gz" | \
          tar zxvf - -C "$(System.DefaultWorkingDirectory)/rootfs/usr/bin/"
      fi
      docker build \
        --build-arg "BUILD_ARCH=${{ parameters.buildArch }}" \
        --build-arg "BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ")" \
        --build-arg "BUILD_FROM=${{ parameters.buildBase }}" \
        --build-arg "BUILD_REF=$(Build.SourceVersion)" \
        --tag "${{ parameters.githubRepository }}-${{ parameters.buildArch }}:$(Build.SourceVersion)" \
        $(dockerTarget)
    displayName: "Build"
