parameters:
  buildArch: "amd64"
  buildBase: "amd64/alpine:3.11.3"
  dockerOrg: "timmo001"
  dockerSlug: "organization"

steps:
  - script: |
      docker info
      docker run --rm --privileged hassioaddons/qemu-user-static:latest
      if [ "${{ parameters.buildArch }}" = "arm32v6" ]; then
        mkdir -p $(System.DefaultWorkingDirectory)/rootfs/usr/bin
        curl -L -s \
          "https://github.com/hassio-addons/qemu-user-static/releases/download/v4.2.0/qemu-arm-static.tar.gz" | \
          tar zxvf - -C "$(System.DefaultWorkingDirectory)/rootfs/usr/bin/"
      fi
      if [ "${{ parameters.buildArch }}" = "arm32v7" ]; then
        mkdir -p $(System.DefaultWorkingDirectory)/rootfs/usr/bin
        curl -L -s \
          "https://github.com/hassio-addons/qemu-user-static/releases/download/v4.2.0/qemu-arm-static.tar.gz" | \
          tar zxvf - -C "$(System.DefaultWorkingDirectory)/rootfs/usr/bin/"
      fi
      if [ "${{ parameters.buildArch }}" = "arm64v8" ]; then
        mkdir -p $(System.DefaultWorkingDirectory)/rootfs/usr/bin
        curl -L -s \
          "https://github.com/hassio-addons/qemu-user-static/releases/download/v4.2.0/qemu-aarch64-static.tar.gz" | \
          tar zxvf - -C "$(System.DefaultWorkingDirectory)/rootfs/usr/bin/"
      fi
      docker pull "${{ parameters.dockerOrg }}/${{ parameters.dockerSlug }}:${{ parameters.buildArch }}-edge"
      docker build \
        --build-arg "BUILD_ARCH=${{ parameters.buildArch }}" \
        --build-arg "BUILD_DATE=$(date +"%Y-%m-%dT%H:%M:%SZ")" \
        --build-arg "BUILD_FROM=${{ parameters.buildBase }}" \
        --build-arg "BUILD_REF=$(Build.SourceVersion)" \
        --cache-from "${{ parameters.dockerOrg }}/${{ parameters.dockerSlug }}:${{ parameters.buildArch }}-edge" \
        --tag "${{ parameters.dockerOrg }}/${{ parameters.dockerSlug }}:${{ parameters.buildArch }}-$(Build.SourceVersion)" \
        $(dockerTarget)
    displayName: "Build"
