parameters:
  packages: 'eslint'
  path: '$(System.DefaultWorkingDirectory)'
  versionNode: '13.x'
  yarnCachePath: '$(Pipeline.Workspace)/.yarn/cache'

jobs:
  - job: 'ESLint'
    steps:
      - template: ../setup/node.yml
      - script: |
          sudo npm -g install ${{ parameters.path }}
        displayName: 'Install'
      - script: |
          eslint $( [[ -e ${{ parameters.path }}/.eslintrc.json ]] || echo '--no-eslintrc' ) --color ${{ parameters.path }}
        displayName: 'Run'
