parameters:
  path: "$(System.DefaultWorkingDirectory)"
  versionNode: "13.x"

jobs:
  - job: "ESLint"
    steps:
      - task: Cache@2
        inputs:
          key: 'yarn | "$(Agent.OS)" | yarn.lock'
          path: ${{ parameters.yarnCachePath }}
          restoreKeys: |
            yarn | "$(Agent.OS)"
            yarn
        displayName: "Cache Yarn Packages"
      - task: NodeTool@0
        inputs:
          versionSpec: ${{ parameters.versionNode }}
        displayName: "Install Node.js"
      - script: |
          yarn install --pure-lockfile --cache-folder $(yarnCachePath)
          sudo yarn global add eslint
        displayName: "Install"
      - script: |
          eslint $( [[ -e ${{ parameters.path }}/.eslintrc.json ]] || echo '--no-eslintrc' ) --color ${{ parameters.path }}
        displayName: "Run"
