parameters:
  path: "$(System.DefaultWorkingDirectory)"

jobs:
  - job: "Prettier"
    pool:
      vmImage: "ubuntu-latest"
    steps:
      - script: sudo yarn global add prettier
        displayName: "Install"
      - script: |
          prettier --check ${{ parameters.path }}/**/*.ts*
          prettier --check ${{ parameters.path }}/**/*.js*
        displayName: "Run"
