parameters:
  path: "$(System.DefaultWorkingDirectory)"

jobs:
  - job: "Prettier"
    steps:
      - script: sudo npm -g install prettier
        displayName: "Install"
      - script: |
          prettier --check ${{ parameters.path }}/**/*.ts*
          prettier --check ${{ parameters.path }}/**/*.js*
        displayName: "Run"
