parameters:
  path: "$(System.DefaultWorkingDirectory)"

jobs:
  - job: "ShellCheck"
    steps:
      - script: |
          find . -type f -print0 | xargs -0 sed -i 's:#!/usr/bin/with-contenv bash:#!/bin/bash:g'
          for file in $(grep -IRl "#\!\(/usr/bin/env \|/bin/\)" --exclude-dir ".git" "${{ parameters.path }}"); do
            if ! shellcheck --external-sources $file; then
              export FAILED=1
              break
            else
              echo "$file OK"
            fi
          done
          if [ "${FAILED}" = "1" ]; then
            exit 1
          fi
        displayName: "Run"
