parameters:
  path: "$(System.DefaultWorkingDirectory)"

jobs:
  - job: "YAMLlint"
    steps:
      - script: sudo apt install yamllint
        displayName: "Install"
      - script: |
          yamllint ${{ parameters.path }}
        displayName: "Run"
